### ISSUE TITLE
Other Diskspace status

### ISSUE THREAD

**Issue by xprimate** [truongan/php.server.status#1]
Good day @truonganvscodesync 
I appreciate your good work.
I have been trying to check the disk status of a backup disk on another partition. On  passing the path as a string as below:
`$disks[] = array("name" => "Backup" , "path" => "/backup") ;`
I usually get 0.00 returned.

I will appreciate a help in fixing this.

The code is run from a cpanel account with php 7.0  on CentOS 6 server.

Thanks.

**Comment by truongan** [comment]
Can you elaborate more on the

> I usually get 0.00 returned.

I don't understand what's your problem is?

**Comment by xprimate** [comment]
Thanks for reaching out.

When I check the disk-space of my backup partition, instead of displaying the disk size is displays **"NaNB/NaNB"**
![Screenshot_2019-04-17 Server status](https://user-images.githubusercontent.com/17166016/56284044-4dd74980-610b-11e9-826e-8244acf0344c.png)

**Comment by truongan** [comment]
What's your total space and free space of "/backup" ?

**Comment by xprimate** [comment]
The total space of "/backup" is 1.8TB and the free space is 397G

Thank.

**Comment by truongan** [comment]
Well, 1.8TiB is not enough to trigger number overflow. The script use two php functions: `disk_total_space` and `disk_free_space` to get and format the disk status information. If your script can't access with those function  "/backup" they will both return "NaN". Can you double check that the permission on that folder?

**Comment by xprimate** [comment]
Thanks for your response.
The permission on the "/backup" partition is 711 and the owner is "root" and the group is also "root" which my account is not part of.
I added my account to the "root" group and "disk" group and tested but the error still remains.
My error log shows:
`disk_total_space(): No such file or directory in /home/username/public_html/statusServer.php on line 164`

Thanks.

**Comment by truongan** [comment]
permission 711 does not allow user in the same group to read that directory. I think you will have to rethink your permission scheme for this to work. Is there any specific reason it got to be 711?

**Comment by xprimate** [comment]
Thanks for your prompt response.
The permission 711 is the default that came with the server for that
partition when it was setup.
Can you suggest a permission that will resolve the issue.
Thanks.

**Comment by truongan** [comment]
I think 750 or 755 is fine. If you need scrict securityn set permission for the backup file, not the backup folder.
