### ISSUE TITLE
Network Traffic Display

### ISSUE THREAD

**Issue by JaysonWonder** [truongan/php.server.status#2]
Thank you for your project. I am not a php pro so may I ask if it is it possible for me to display the Network Traffic by default?

I have vnstats installed and functioning correctly and it can disply when using thei URL only: http://pi/checkup.php?showtraffic=m

It will not work if I try to include the checkup.php in another file such as index.php

I would like the Network Traffic to display simply by http://rpi3/checkup.php

Is this possible?

Thanks,

**Comment by truongan** [comment]
Find this line 
```
if (!isset($_GET['showtraffic']) || $_GET['showtraffic'] ==  false) die();
```
and comment it out, that should do it.

**Comment by JaysonWonder** [comment]
Thank you for your quick reply. This displays the table and title but where the data is suppose to show I get this error.
`Unknown parameter "-". Use --help for help.`
I am trying to learn php so I am just a beginner so please excuse my lack of knowledge. Any help is appreciated.

Thanks,

**Comment by JaysonWonder** [comment]
Please disregard, I found the issue, I changed this:
exec('vnstat -' . $_GET['showtraffic'], $traffic_arr, $status);
to this:
exec('vnstat -m' . $_GET['showtraffic'], $traffic_arr, $status);
I'm happy. Thanks

**Comment by truongan** [comment]
I didn't have the need to embed the script in another file so I never really tested this. Glad you were able to figure it out :)
