### ISSUE TITLE
Top RAM user && Top CPU user Problem

### ISSUE THREAD

**Issue by ghost** [truongan/php.server.status#5]
https://prnt.sc/r2inwi

**Comment by truongan** [comment]
What's the problem?

**Comment by ghost** [comment]
As you can see in the picture there is nothing displayed at Top RAM user and Top CPU user only commands

**Comment by truongan** [comment]
Perhaps it was a misleading label to say the least. That section was meant to show what process (command) use the most RAM and CPU percentage.
